openapi: 3.0.3
info:
  title: Rokwire Notification Building Block API
  description: Notification Building Block API Documentation
  version: 1.20.0
servers:
  - url: 'https://api.rokwire.illinois.edu/notifications'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/notifications'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/notifications'
    description: Development server
  - url: 'http://localhost/notifications'
    description: Local server
tags:
  - name: Admin
    description: Clients administration applications APIs.
  - name: Internal
    description: Internal applications APIs.
  - name: Client
    description: Client applications APIs.
paths:  
  #Internal
  /api/int/message:
    $ref: "./resources/internal/message.yaml"
  /api/int/v2/message:
    $ref: "./resources/internal/v2/message.yaml"
  /api/int/mail:
    $ref: "./resources/internal/mail.yaml"
  #Client
  /api/token:
    $ref: "./resources/client/token.yaml"
  /api/user:
    $ref: "./resources/client/user.yaml"
  /api/message:
    $ref: "./resources/client/message/message.yaml"
  /api/messages:
    $ref: "./resources/client/message/messages.yaml"
  /api/messages/read:
    $ref: "./resources/client/message/messages-read.yaml"
  /api/messages/stats:
    $ref: "./resources/client/message/messages-stats.yaml"  
  /api/message/{id}:
    $ref: "./resources/client/message/messages-id.yaml"
  /api/message/{id}/read:
    $ref: "./resources/client/message/message-read.yaml"
  /api/topics:
    $ref: "./resources/client/topic/topics.yaml"
  /api/topic/{topic}/messages:
    $ref: "./resources/client/topic/topics-messages.yaml"
  /api/topic/{topic}/subscribe:
    $ref: "./resources/client/topic/topics-subscribe.yaml"
  /api/topic/{topic}/unsubscribe:
    $ref: "./resources/client/topic/topics-unsubscribe.yaml"
  #Admin
  /api/admin/app-versions:
    $ref: "./resources/admin/app-versions.yaml"
  /api/admin/app-platforms:
    $ref: "./resources/admin/app-platforms.yaml"
  /api/admin/topics:
    $ref: "./resources/admin/topic/topics.yaml"
  /api/admin/topic:
    $ref: "./resources/admin/topic/topic.yaml"
  /api/admin/messages:
    $ref: "./resources/admin/message/messages.yaml"
  /api/admin/message:
    $ref: "./resources/admin/message/message.yaml"
  /api/admin/messages{id}:
    $ref: "./resources/admin/message/messages-id.yaml"
  /api/admin/messages/stats/source/{source}:
    $ref: "./resources/admin/messages/stats/source.yaml"    

  #BBs
  /api/bbs/messages:
    $ref: "./resources/bbs/messages.yaml"
  /api/bbs/messages/{message-id}/recipients:
    $ref: "./resources/bbs/message-id/recipients.yaml"
  /api/bbs/message:
    $ref: "./resources/bbs/message.yaml"
  /api/bbs/{id}:
    $ref: "./resources/bbs/message-id.yaml"
  /api/bbs/mail:
    $ref: "./resources/bbs/mail.yaml"

    
components:
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"